= Rust note
Pascal Munerot <pascal.munerot@gmail.com>
v0.1, January 1, 2020: Initial version

== Colophon

Version: {revnumber}

Version Date: {revdate}

Version Notes: {revremark}

== Table of content

:toc-title: Table of content
:toclevels: 3
:toc: auto



## const and global variables (static)

const are like C preprocessor defines and have no real address.
[source,rust]
--
const TEST: u32 = 100; // <1> behaves like a C preprocess define clause
static a : u32=8;
--


## masking variables by the same name

It is possible to mask a variable in the same block scope with several subsequent let statements.

[source,rust]
--
let a : u32=8; let a = a.into(); //check syntax
--

## Loops

- for in loop has exclusive upper bound -> 1..11 (range) means 1 to 10.

[source,rust]
--
for (pos, y) in (30..41).enumerate() { println!("{}: {}", pos, y); }
--

- use enumerate() to obtain pair of positions and value

## Memory

Heap allocation is made on stack (address) but the data is on the heap.
Use Box::new(5) for allocating on the heap.
Use star to follow the pointer i.e. dereference.

## Functions

the last value in a function is returned if there is no semicolon on the last statement otherwise the value is discarded.

## Match specific range

 `...` (3 dots) instead of `..` (2 dots) are needed in match embedded ranges (e.g. 1...999).
Upper bound is inclusive contrary to that of for in loops.

